name: Enterprise DevOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/enterprise-devops-app

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} ./app

      - name: Test Docker image
        run: |
          docker run -d -p 8080:80 --name test-app $IMAGE_NAME:${{ github.sha }}
          sleep 5
          curl --fail http://localhost:8080

      - name: Stop test container
        if: always()
        run: |
          docker stop test-app || true
          docker rm test-app || true

      - name: Trivy security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Login to GHCR
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build-test-scan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl start docker

            sudo docker login ghcr.io \
              -u ${{ github.actor }} \
              -p ${{ secrets.GITHUB_TOKEN }}

            sudo docker pull ${{ env.IMAGE_NAME }}:latest

            sudo docker stop enterprise-devops-app || true
            sudo docker rm enterprise-devops-app || true

            sudo docker run -d \
            --name enterprise-devops-app \
            --restart unless-stopped \
            --log-driver=awslogs \
            --log-opt awslogs-region=ap-south-1 \
            --log-opt awslogs-group=enterprise-devops-application \
            --log-opt awslogs-stream=enterprise-devops-app \
            -p 80:80 \
            ${{ env.IMAGE_NAME }}:latest

            sudo docker image prune -f